import {colors} from './src/styles/colors'

const config = {
	mode: 'jit',
	content: [
		"./src/**/*.{html,js,jsx,ts,tsx,css}",
		'./src/pages/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/components/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/app/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/stories/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/assets/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/lib/**/*.{js,ts,jsx,tsx,mdx}',
	],
	darkMode: ['class', '[data-theme="dark"]'],
	theme: {
		extend: {
			screens: {
				'wide': {min: '1120px'},
				'dt': {min: '881px'},
				'mo': {max: '880px'}
			},
			fontFamily: {
				sans: ['Pretendard', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'sans-serif', ],
				prosto: ['ProstoOne', 'sans-serif'],
			},
			fontSize: {
				// Display
				'display-lg': ['4rem', { lineHeight: '5.4rem', letterSpacing: '-0.12rem', fontWeight: 700 }],
				'display-lg-en': ['4rem', { lineHeight: '5.4rem', letterSpacing: '-0.02rem', fontWeight: 700 }],
				'display-lg-ja': ['4rem', { lineHeight: '5.4rem', letterSpacing: '-0.06rem', fontWeight: 700 }],
				'display-lg-zh': ['4rem', { lineHeight: '5.4rem', letterSpacing: '-0.06rem', fontWeight: 700 }],
				'display-md': ['3rem', { lineHeight: '4.05rem', letterSpacing: '-0.09rem', fontWeight: 700 }],
				'display-md-en': ['3rem', { lineHeight: '4.05rem', letterSpacing: '-0.015rem', fontWeight: 700 }],
				'display-md-ja': ['3rem', { lineHeight: '4.05rem', letterSpacing: '-0.045rem', fontWeight: 700 }],
				'display-md-zh': ['3rem', { lineHeight: '4.05rem', letterSpacing: '-0.045rem', fontWeight: 700 }],
				
				// Heading
				'heading-3xl': ['2.75rem', { lineHeight: '3.85rem', letterSpacing: '-0.055rem', fontWeight: 700 }],
				'heading-3xl-en': ['2.75rem', { lineHeight: '3.85rem', letterSpacing: '0rem', fontWeight: 700 }],
				'heading-3xl-ja': ['2.75rem', { lineHeight: '3.85rem', letterSpacing: '-0.0275rem', fontWeight: 700 }],
				'heading-3xl-zh': ['2.75rem', { lineHeight: '3.85rem', letterSpacing: '-0.0275rem', fontWeight: 700 }],
				'heading-2xl': ['2.25rem', { lineHeight: '3.15rem', letterSpacing: '-0.045rem', fontWeight: 700 }],
				'heading-2xl-en': ['2.25rem', { lineHeight: '3.15rem', letterSpacing: '0rem', fontWeight: 700 }],
				'heading-2xl-ja': ['2.25rem', { lineHeight: '3.15rem', letterSpacing: '-0.0225rem', fontWeight: 700 }],
				'heading-2xl-zh': ['2.25rem', { lineHeight: '3.15rem', letterSpacing: '-0.0225rem', fontWeight: 700 }],
				'heading-xl': ['2rem', { lineHeight: '2.8rem', letterSpacing: '-0.04rem', fontWeight: 700 }],
				'heading-xl-en': ['2rem', { lineHeight: '2.8rem', letterSpacing: '0rem', fontWeight: 700 }],
				'heading-xl-ja': ['2rem', { lineHeight: '2.8rem', letterSpacing: '-0.02rem', fontWeight: 700 }],
				'heading-xl-zh': ['2rem', { lineHeight: '2.8rem', letterSpacing: '-0.02rem', fontWeight: 700 }],
				'heading-lg': ['1.75rem', { lineHeight: '2.45rem', letterSpacing: '-0.035rem', fontWeight: 600 }],
				'heading-lg-en': ['1.75rem', { lineHeight: '2.45rem', letterSpacing: '0rem', fontWeight: 600 }],
				'heading-lg-ja': ['1.75rem', { lineHeight: '2.45rem', letterSpacing: '-0.0175rem', fontWeight: 600 }],
				'heading-lg-zh': ['1.75rem', { lineHeight: '2.45rem', letterSpacing: '-0.0175rem', fontWeight: 600 }],
				'heading-md': ['1.5rem', { lineHeight: '2.1rem', letterSpacing: '-0.03rem', fontWeight: 600 }],
				'heading-md-en': ['1.5rem', { lineHeight: '2.1rem', letterSpacing: '0rem', fontWeight: 600 }],
				'heading-md-ja': ['1.5rem', { lineHeight: '2.1rem', letterSpacing: '-0.015rem', fontWeight: 600 }],
				'heading-md-zh': ['1.5rem', { lineHeight: '2.1rem', letterSpacing: '-0.015rem', fontWeight: 600 }],
				'heading-sm': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.025rem', fontWeight: 600 }],
				'heading-sm-en': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '0rem', fontWeight: 600 }],
				'heading-sm-ja': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.0125rem', fontWeight: 600 }],
				'heading-sm-zh': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.0125rem', fontWeight: 600 }],
				'heading-xs': ['1.125rem', { lineHeight: '1.575rem', letterSpacing: '-0.0225rem', fontWeight: 700 }],
				'heading-xs-en': ['1.125rem', { lineHeight: '1.575rem', letterSpacing: '0rem', fontWeight: 700 }],
				'heading-xs-ja': ['1.125rem', { lineHeight: '1.575rem', letterSpacing: '-0.01125rem', fontWeight: 700 }],
				'heading-xs-zh': ['1.125rem', { lineHeight: '1.575rem', letterSpacing: '-0.01125rem', fontWeight: 700 }],
				'heading-2xs': ['1rem', { lineHeight: '1.4rem', letterSpacing: '-0.02rem', fontWeight: 700 }],
				'heading-2xs-en': ['1rem', { lineHeight: '1.4rem', letterSpacing: '0rem', fontWeight: 700 }],
				'heading-2xs-ja': ['1rem', { lineHeight: '1.4rem', letterSpacing: '-0.01rem', fontWeight: 700 }],
				'heading-2xs-zh': ['1rem', { lineHeight: '1.4rem', letterSpacing: '-0.01rem', fontWeight: 700 }],
				
				// Body
				'body-3xl': ['1.25rem', { lineHeight: '1.875rem', letterSpacing: '-0.01875rem' }],
				'body-3xl-en': ['1.25rem', { lineHeight: '1.875rem', letterSpacing: '0rem' }],
				'body-3xl-ja': ['1.25rem', { lineHeight: '1.875rem', letterSpacing: '-0.00625rem' }],
				'body-3xl-zh': ['1.25rem', { lineHeight: '1.875rem', letterSpacing: '-0.00625rem' }],
				'body-2xl': ['1.125rem', { lineHeight: '1.6875rem', letterSpacing: '-0.016875rem' }],
				'body-2xl-en': ['1.125rem', { lineHeight: '1.6875rem', letterSpacing: '0rem' }],
				'body-2xl-ja': ['1.125rem', { lineHeight: '1.6875rem', letterSpacing: '-0.005625rem' }],
				'body-2xl-zh': ['1.125rem', { lineHeight: '1.6875rem', letterSpacing: '-0.005625rem' }],
				'body-xl': ['1rem', { lineHeight: '1.5rem', letterSpacing: '-0.015rem' }],
				'body-xl-en': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0rem' }],
				'body-xl-ja': ['1rem', { lineHeight: '1.5rem', letterSpacing: '-0.005rem' }],
				'body-xl-zh': ['1rem', { lineHeight: '1.5rem', letterSpacing: '-0.005rem' }],
				'body-lg': ['0.94rem', { lineHeight: '1.41rem', letterSpacing: '-0.0141rem' }],
				'body-lg-en': ['0.94rem', { lineHeight: '1.41rem', letterSpacing: '0rem' }],
				'body-lg-ja': ['0.94rem', { lineHeight: '1.41rem', letterSpacing: '-0.0047rem' }],
				'body-lg-zh': ['0.94rem', { lineHeight: '1.41rem', letterSpacing: '-0.0047rem' }],
				'body-md': ['0.87rem', { lineHeight: '1.305rem', letterSpacing: '-0.01305rem' }],
				'body-md-en': ['0.87rem', { lineHeight: '1.305rem', letterSpacing: '0rem' }],
				'body-md-ja': ['0.87rem', { lineHeight: '1.305rem', letterSpacing: '-0.00435rem' }],
				'body-md-zh': ['0.87rem', { lineHeight: '1.305rem', letterSpacing: '-0.00435rem' }],
				'body-sm': ['0.81rem', { lineHeight: '1.215rem', letterSpacing: '-0.0081rem' }],
				'body-sm-en': ['0.81rem', { lineHeight: '1.215rem', letterSpacing: '0rem' }],
				'body-sm-ja': ['0.81rem', { lineHeight: '1.215rem', letterSpacing: '0rem' }],
				'body-sm-zh': ['0.81rem', { lineHeight: '1.215rem', letterSpacing: '0rem' }],
				'body-xs': ['0.75rem', { lineHeight: '1.125rem', letterSpacing: '-0.0075rem' }],
				'body-xs-en': ['0.75rem', { lineHeight: '1.125rem', letterSpacing: '0rem' }],
				'body-xs-ja': ['0.75rem', { lineHeight: '1.125rem', letterSpacing: '0rem' }],
				'body-xs-zh': ['0.75rem', { lineHeight: '1.125rem', letterSpacing: '0rem' }],
				'body-2xs': ['0.69rem', { lineHeight: '1.035rem', letterSpacing: '-0.0069rem' }],
				'body-2xs-en': ['0.69rem', { lineHeight: '1.035rem', letterSpacing: '0rem' }],
				'body-2xs-ja': ['0.69rem', { lineHeight: '1.035rem', letterSpacing: '0rem' }],
				'body-2xs-zh': ['0.69rem', { lineHeight: '1.035rem', letterSpacing: '0rem' }],
				
				// Label
				'label-2xl': ['1.125rem', { lineHeight: '1.575rem', letterSpacing: '-0.016875rem', fontWeight: 500 }],
				'label-2xl-en': ['1.125rem', { lineHeight: '1.575rem', letterSpacing: '0rem', fontWeight: 500 }],
				'label-2xl-ja': ['1.125rem', { lineHeight: '1.575rem', letterSpacing: '-0.005625rem', fontWeight: 500 }],
				'label-2xl-zh': ['1.125rem', { lineHeight: '1.575rem', letterSpacing: '-0.005625rem', fontWeight: 500 }],
				'label-xl': ['1rem', { lineHeight: '1.4rem', letterSpacing: '-0.015rem', fontWeight: 500 }],
				'label-xl-en': ['1rem', { lineHeight: '1.4rem', letterSpacing: '0rem', fontWeight: 500 }],
				'label-xl-ja': ['1rem', { lineHeight: '1.4rem', letterSpacing: '-0.005rem', fontWeight: 500 }],
				'label-xl-zh': ['1rem', { lineHeight: '1.4rem', letterSpacing: '-0.005rem', fontWeight: 500 }],
				'label-lg': ['0.94rem', { lineHeight: '1.316rem', letterSpacing: '-0.0141rem', fontWeight: 500 }],
				'label-lg-en': ['0.94rem', { lineHeight: '1.316rem', letterSpacing: '0rem', fontWeight: 500 }],
				'label-lg-ja': ['0.94rem', { lineHeight: '1.316rem', letterSpacing: '-0.0047rem', fontWeight: 500 }],
				'label-lg-zh': ['0.94rem', { lineHeight: '1.316rem', letterSpacing: '-0.0047rem', fontWeight: 500 }],
				'label-md': ['0.87rem', { lineHeight: '1.218rem', letterSpacing: '-0.01305rem', fontWeight: 500 }],
				'label-md-en': ['0.875rem', { lineHeight: '1.225rem', letterSpacing: '0rem', fontWeight: 500 }],
				'label-md-ja': ['0.875rem', { lineHeight: '1.225rem', letterSpacing: '-0.00438rem', fontWeight: 500 }],
				'label-md-zh': ['0.875rem', { lineHeight: '1.225rem', letterSpacing: '-0.00438rem', fontWeight: 500 }],
				'label-sm': ['0.81rem', { lineHeight: '1.134rem', letterSpacing: '-0.0081rem', fontWeight: 500 }],
				'label-sm-en': ['0.81rem', { lineHeight: '1.134rem', letterSpacing: '0rem', fontWeight: 500 }],
				'label-sm-ja': ['0.81rem', { lineHeight: '1.134rem', letterSpacing: '0rem', fontWeight: 500 }],
				'label-sm-zh': ['0.81rem', { lineHeight: '1.134rem', letterSpacing: '0rem', fontWeight: 500 }],
				'label-xs': ['0.75rem', { lineHeight: '1.05rem', letterSpacing: '-0.0075rem', fontWeight: 500 }],
				'label-xs-en': ['0.75rem', { lineHeight: '1.05rem', letterSpacing: '0rem', fontWeight: 500 }],
				'label-xs-ja': ['0.75rem', { lineHeight: '1.05rem', letterSpacing: '0rem', fontWeight: 500 }],
				'label-xs-zh': ['0.75rem', { lineHeight: '1.05rem', letterSpacing: '0rem', fontWeight: 500 }],
				'label-2xs': ['0.69rem', { lineHeight: '0.966rem', letterSpacing: '-0.0069rem', fontWeight: 500 }],
				'label-2xs-en': ['0.69rem', { lineHeight: '0.966rem', letterSpacing: '0rem', fontWeight: 500 }],
				'label-2xs-ja': ['0.69rem', { lineHeight: '0.966rem', letterSpacing: '0rem', fontWeight: 500 }],
				'label-2xs-zh': ['0.69rem', { lineHeight: '0.966rem', letterSpacing: '0rem', fontWeight: 500 }],
				'button-xl': ['1.125rem', { lineHeight: '1.125rem', letterSpacing: '-0.0225rem', fontWeight: 600 }],
				'button-xl-en': ['1.125rem', { lineHeight: '1.125rem', letterSpacing: '0rem', fontWeight: 600 }],
				'button-xl-ja': ['1.125rem', { lineHeight: '1.125rem', letterSpacing: '-0.01125rem', fontWeight: 600 }],
				'button-xl-zh': ['1.125rem', { lineHeight: '1.125rem', letterSpacing: '-0.01125rem', fontWeight: 600 }],
				'button-lg': ['1rem', { lineHeight: '1rem', letterSpacing: '-0.02rem', fontWeight: 600 }],
				'button-lg-en': ['1rem', { lineHeight: '1rem', letterSpacing: '0rem', fontWeight: 600 }],
				'button-lg-ja': ['1rem', { lineHeight: '1rem', letterSpacing: '-0.01rem', fontWeight: 600 }],
				'button-lg-zh': ['1rem', { lineHeight: '1rem', letterSpacing: '-0.01rem', fontWeight: 600 }],
				'button-md': ['0.94rem', { lineHeight: '0.94rem', letterSpacing: '-0.0188rem', fontWeight: 600 }],
				'button-md-en': ['0.94rem', { lineHeight: '0.94rem', letterSpacing: '0rem', fontWeight: 600 }],
				'button-md-ja': ['0.94rem', { lineHeight: '0.94rem', letterSpacing: '-0.0094rem', fontWeight: 600 }],
				'button-md-zh': ['0.94rem', { lineHeight: '0.94rem', letterSpacing: '-0.0094rem', fontWeight: 600 }],
				'button-sm': ['0.87rem', { lineHeight: '0.87rem', letterSpacing: '-0.0174rem', fontWeight: 600 }],
				'button-sm-en': ['0.87rem', { lineHeight: '0.87rem', letterSpacing: '0rem', fontWeight: 600 }],
				'button-sm-ja': ['0.87rem', { lineHeight: '0.87rem', letterSpacing: '-0.0087rem', fontWeight: 600 }],
				'button-sm-zh': ['0.87rem', { lineHeight: '0.87rem', letterSpacing: '-0.0087rem', fontWeight: 600 }],
				'button-xs': ['0.812rem', { lineHeight: '0.812rem', letterSpacing: '-0.01625rem', fontWeight: 600 }],
				'button-xs-en': ['0.812rem', { lineHeight: '0.812rem', letterSpacing: '0rem', fontWeight: 600 }],
				'button-xs-ja': ['0.812rem', { lineHeight: '0.812rem', letterSpacing: '-0.00813rem', fontWeight: 600 }],
				'button-xs-zh': ['0.812rem', { lineHeight: '0.812rem', letterSpacing: '-0.00813rem', fontWeight: 600 }],
			},
			padding: { // px 값 기준으로 명칭 변경하여 사용
				0: '0px',
				1: '1px',
				2: '2px',
				3: '3px',
				4: '4px',
				5: '5px',
				6: '6px',
				7: '7px',
				8: '8px',
				9: '9px',
				10: '10px',
				11: '11px',
				12: '12px',
				13: '13px',
				14: '14px',
				15: '15px',
				16: '16px',
				17: '17px',
				18: '18px',
				19: '19px',
				20: '20px',
				21: '21px',
				22: '22px',
				23: '23px',
				24: '24px',
				25: '25px',
				26: '26px',
				27: '27px',
				28: '28px',
				29: '29px',
				30: '30px',
				31: '31px',
				32: '32px',
				33: '33px',
				34: '34px',
				35: '35px',
				36: '36px',
				37: '37px',
				38: '38px',
				39: '39px',
				40: '40px',
				41: '41px',
				42: '42px',
				43: '43px',
				44: '44px',
				45: '45px',
				46: '46px',
				47: '47px',
				48: '48px',
				49: '49px',
				50: '50px',
				51: '51px',
				52: '52px',
				53: '53px',
				54: '54px',
				55: '55px',
				56: '56px',
				64: '64px',
				65: '65px',
				66: '66px',
				67: '67px',
				68: '68px',
				69: '69px',
				70: '70px',
				71: '71px',
				72: '72px',
				73: '73px',
				74: '74px',
				75: '75px',
				76: '76px',
				77: '77px',
				78: '78px',
				79: '79px',
				80: '80px',
				96: '96px',
				112: '112px',
				128: '128px',
				144: '144px',
				160: '160px',
				176: '176px',
				208: '208px',
				224: '224px',
				256: '256px',
				288: '288px',
				320: '320px',
				384: '384px'
			},
			margin: { // px 값 기준으로 명칭 변경하여 사용
				'1/5': '20%',
				0: '0px',
				1: '1px',
				2: '2px',
				3: '3px',
				4: '4px',
				5: '5px',
				6: '6px',
				7: '7px',
				8: '8px',
				9: '9px',
				10: '10px',
				11: '11px',
				12: '12px',
				13: '13px',
				14: '14px',
				15: '15px',
				16: '16px',
				17: '17px',
				18: '18px',
				19: '19px',
				20: '20px',
				21: '21px',
				22: '22px',
				23: '23px',
				24: '24px',
				25: '25px',
				26: '26px',
				27: '27px',
				28: '28px',
				29: '29px',
				30: '30px',
				31: '31px',
				32: '32px',
				33: '33px',
				34: '34px',
				35: '35px',
				36: '36px',
				37: '37px',
				38: '38px',
				39: '39px',
				40: '40px',
				41: '41px',
				42: '42px',
				43: '43px',
				44: '44px',
				45: '45px',
				46: '46px',
				47: '47px',
				48: '48px',
				49: '49px',
				50: '50px',
				51: '51px',
				52: '52px',
				56: '56px',
				64: '64px',
				65: '65px',
				66: '66px',
				67: '67px',
				68: '68px',
				69: '69px',
				70: '70px',
				71: '71px',
				72: '72px',
				73: '73px',
				74: '74px',
				75: '75px',
				76: '76px',
				77: '77px',
				78: '78px',
				79: '79px',
				80: '80px',
				96: '96px',
				112: '112px',
				128: '128px',
				144: '144px',
				160: '160px',
				176: '176px',
				208: '208px',
				224: '224px',
				256: '256px',
				288: '288px',
				320: '320px',
				384: '384px'
			},
			gap: {
				0: '0px',
				1: '1px',
				2: '2px',
				3: '3px',
				4: '4px',
				5: '5px',
				6: '6px',
				7: '7px',
				8: '8px',
				9: '9px',
				10: '10px',
				11: '11px',
				12: '12px',
				13: '13px',
				14: '14px',
				15: '15px',
				16: '16px',
				17: '17px',
				18: '18px',
				19: '19px',
				20: '20px',
				21: '21px',
				22: '22px',
				23: '23px',
				24: '24px',
				25: '25px',
				26: '26px',
				27: '27px',
				28: '28px',
				29: '29px',
				30: '30px',
				31: '31px',
				32: '32px',
				33: '33px',
				34: '34px',
				35: '35px',
				36: '36px',
				37: '37px',
				38: '38px',
				39: '39px',
				40: '40px',
				41: '41px',
				42: '42px',
				43: '43px',
				44: '44px',
				45: '45px',
				46: '46px',
				47: '47px',
				48: '48px',
				49: '49px',
				50: '50px',
				51: '51px',
				52: '52px',
				56: '56px',
				64: '64px',
				65: '65px',
				66: '66px',
				67: '67px',
				68: '68px',
				69: '69px',
				70: '70px',
				71: '71px',
				72: '72px',
				73: '73px',
				74: '74px',
				75: '75px',
				76: '76px',
				77: '77px',
				78: '78px',
				79: '79px',
				80: '80px',
				96: '96px',
				112: '112px',
				128: '128px',
				144: '144px',
				160: '160px',
				176: '176px',
				208: '208px',
				224: '224px',
				256: '256px',
				288: '288px',
				320: '320px',
				384: '384px'
			},
			space: { // rem 값 기준으로 명칭 변경하여 사용
				0: '0rem',
				2: '2rem',
				4: '4rem',
				6: '6rem',
				8: '8rem',
				10: '10rem',
				12: '12rem',
				14: '14rem',
				16: '16rem',
				20: '20rem',
				24: '24rem',
				28: '28rem',
				32: '32rem',
				36: '36rem',
				40: '40rem',
				44: '44rem',
				48: '48rem',
				56: '56rem',
				64: '64rem',
				72: '72rem',
				80: '80rem',
				96: '96rem',
				112: '112rem',
				128: '128rem',
				160: '160rem',
				200: '200rem',
			},
			borderRadius: { // px 값 기준으로 명칭 변경하여 사용
				0: '0px',
				2: '2px',
				4: '4px',
				6: '6px',
				8: '8px',
				10: '10px',
				12: '12px',
				14: '14px',
				16: '16px',
				20: '20px',
				24: '24px',
				32: '32px',
				40: '40px',
				999: '999px'
			},
			colors: {
				white: colors.common_100,
				black: colors.common_0,
				neutral: {
					5: colors.neutral_5,
					10: colors.neutral_10,
					20: colors.neutral_20,
					30: colors.neutral_30,
					40: colors.neutral_40,
					50: colors.neutral_50,
					60: colors.neutral_60,
					70: colors.neutral_70,
					80: colors.neutral_80,
					90: colors.neutral_90,
					95: colors.neutral_95,
					99: colors.neutral_99,
				},
				red: {
					5: colors.red_5,
					10: colors.red_10,
					20: colors.red_20,
					30: colors.red_30,
					40: colors.red_40,
					50: colors.red_50,
					60: colors.red_60,
					70: colors.red_70,
					80: colors.red_80,
					90: colors.red_90,
					95: colors.red_95,
					99: colors.red_99,
				},
				orange: {
					5: colors.orange_5,
					10: colors.orange_10,
					20: colors.orange_20,
					30: colors.orange_30,
					40: colors.orange_40,
					50: colors.orange_50,
					60: colors.orange_60,
					70: colors.orange_70,
					80: colors.orange_80,
					90: colors.orange_90,
					95: colors.orange_95,
					99: colors.orange_99,
				},
				yellow: {
					5: colors.yellow_5,
					10: colors.yellow_10,
					20: colors.yellow_20,
					30: colors.yellow_30,
					40: colors.yellow_40,
					50: colors.yellow_50,
					60: colors.yellow_60,
					70: colors.yellow_70,
					80: colors.yellow_80,
					90: colors.yellow_90,
					95: colors.yellow_95,
					99: colors.yellow_99,
				},
				lime: {
					5: colors.lime_5,
					10: colors.lime_10,
					20: colors.lime_20,
					30: colors.lime_30,
					40: colors.lime_40,
					50: colors.lime_50,
					60: colors.lime_60,
					70: colors.lime_70,
					80: colors.lime_80,
					90: colors.lime_90,
					95: colors.lime_95,
					99: colors.lime_99,
				},
				green: {
					5: colors.green_5,
					10: colors.green_10,
					20: colors.green_20,
					30: colors.green_30,
					40: colors.green_40,
					50: colors.green_50,
					60: colors.green_60,
					70: colors.green_70,
					80: colors.green_80,
					90: colors.green_90,
					95: colors.green_95,
					99: colors.green_99,
				},
				teal: {
					5: colors.teal_5,
					10: colors.teal_10,
					20: colors.teal_20,
					30: colors.teal_30,
					40: colors.teal_40,
					50: colors.teal_50,
					60: colors.teal_60,
					70: colors.teal_70,
					80: colors.teal_80,
					90: colors.teal_90,
					95: colors.teal_95,
					99: colors.teal_99,
				},
				lightblue: {
					5: colors.lightblue_5,
					10: colors.lightblue_10,
					20: colors.lightblue_20,
					30: colors.lightblue_30,
					40: colors.lightblue_40,
					50: colors.lightblue_50,
					60: colors.lightblue_60,
					70: colors.lightblue_70,
					80: colors.lightblue_80,
					90: colors.lightblue_90,
					95: colors.lightblue_95,
					99: colors.lightblue_99,
				},
				blue: {
					5: colors.blue_5,
					10: colors.blue_10,
					20: colors.blue_20,
					30: colors.blue_30,
					40: colors.blue_40,
					50: colors.blue_50,
					60: colors.blue_60,
					70: colors.blue_70,
					80: colors.blue_80,
					90: colors.blue_90,
					95: colors.blue_95,
					99: colors.blue_99,
				},
				violet: {
					5: colors.violet_5,
					10: colors.violet_10,
					20: colors.violet_20,
					30: colors.violet_30,
					40: colors.violet_40,
					50: colors.violet_50,
					60: colors.violet_60,
					70: colors.violet_70,
					80: colors.violet_80,
					90: colors.violet_90,
					95: colors.violet_95,
					99: colors.violet_99,
				},
				purple: {
					5: colors.purple_5,
					10: colors.purple_10,
					20: colors.purple_20,
					30: colors.purple_30,
					40: colors.purple_40,
					50: colors.purple_50,
					60: colors.purple_60,
					70: colors.purple_70,
					80: colors.purple_80,
					90: colors.purple_90,
					95: colors.purple_95,
					99: colors.purple_99,
				},
				pink: {
					5: colors.pink_5,
					10: colors.pink_10,
					20: colors.pink_20,
					30: colors.pink_30,
					40: colors.pink_40,
					50: colors.pink_50,
					60: colors.pink_60,
					70: colors.pink_70,
					80: colors.pink_80,
					90: colors.pink_90,
					95: colors.pink_95,
					99: colors.pink_99,
				},
				dynamic: {
					text: {
						neutral: {
							inverse: 'var(--text-neutral-inverse-color)',
							disabled: 'var(--text-neutral-disabled-color)',
							primary: 'var(--text-neutral-primary-color)',
							secondary: 'var(--text-neutral-secondary-color)',
							tertiary: 'var(--text-neutral-tertiary-color)',
							quarternary: 'var(--text-neutral-quarternary-color)',
						},
						brand: {
							'primary-bold': 'var(--text-brand-primary-bold-color)',
							'primary-subtle': 'var(--text-brand-primary-subtle-color)',
							primary: 'var(--text-brand-primary-color)',
							inverse: 'var(--text-brand-inverse-color)',
						},
						caution: {
							'primary-bold': 'var(--text-caution-primary-bold-color)',
							'primary-subtle': 'var(--text-caution-primary-subtle-color)',
							primary: 'var(--text-caution-primary-color)',
							inverse: 'var(--text-caution-inverse-color)',
						},
						positive: {
							'primary-bold': 'var(--text-positive-primary-bold-color)',
							'primary-subtle': 'var(--text-positive-primary-subtle-color)',
							primary: 'var(--text-positive-primary-color)',
							inverse: 'var(--text-positive-inverse-color)',
						},
						info: {
							'primary-bold': 'var(--text-info-primary-bold-color)',
							'primary-subtle': 'var(--text-info-primary-subtle-color)',
							primary: 'var(--text-info-primary-color)',
							inverse: 'var(--text-info-inverse-color)',
						},
						negative: {
							'primary-bold': 'var(--text-negative-primary-bold-color)',
							'primary-subtle': 'var(--text-negative-primary-subtle-color)',
							primary: 'var(--text-negative-primary-color)',
							inverse: 'var(--text-negative-inverse-color)',
						},
						alert: {
							primary: 'var(--text-alert-primary-color)',
						},
						other: {
							red: 'var(--text-other-red-color)',
							'red-subtle': 'var(--text-other-red-subtle-color)',
							'red-bold': 'var(--text-other-red-bold-color)',
							yellow: 'var(--text-other-yellow-color)',
							'yellow-subtle': 'var(--text-other-yellow-subtle-color)',
							'yellow-bold': 'var(--text-other-yellow-bold-color)',
							teal: 'var(--text-other-teal-color)',
							'teal-subtle': 'var(--text-other-teal-subtle-color)',
							'teal-bold': 'var(--text-other-teal-bold-color)',
							lime: 'var(--text-other-lime-color)',
							'lime-subtle': 'var(--text-other-lime-subtle-color)',
							'lime-bold': 'var(--text-other-lime-bold-color)',
							purple: 'var(--text-other-purple-color)',
							'purple-subtle': 'var(--text-other-purple-subtle-color)',
							'purple-bold': 'var(--text-other-purple-bold-color)',
							violet: 'var(--text-other-violet-color)',
							'violet-subtle': 'var(--text-other-violet-subtle-color)',
							'violet-bold': 'var(--text-other-violet-bold-color)',
							pink: 'var(--text-other-pink-color)',
							'pink-subtle': 'var(--text-other-pink-subtle-color)',
							'pink-bold': 'var(--text-other-pink-bold-color)',
							lightblue: 'var(--text-other-lightblue-color)',
							'lightblue-subtle': 'var(--text-other-lightblue-subtle-color)',
							'lightblue-bold': 'var(--text-other-lightblue-bold-color)',
							green: 'var(--text-other-green-color)',
							'green-subtle': 'var(--text-other-green-subtle-color)',
							'green-bold': 'var(--text-other-green-bold-color)',
							blue: 'var(--text-other-blue-color)',
							'blue-subtle': 'var(--text-other-blue-subtle-color)',
							'blue-bold': 'var(--text-other-blue-bold-color)',
							orange: 'var(--text-other-orange-color)',
							'orange-subtle': 'var(--text-other-orange-subtle-color)',
							'orange-bold': 'var(--text-other-orange-bold-color)',
							'red-inverse': 'var(--text-other-red-inverse-color)',
							'yellow-inverse': 'var(--text-other-yellow-inverse-color)',
							'orange-inverse': 'var(--text-other-orange-inverse-color)',
							'lime-inverse': 'var(--text-other-lime-inverse-color)',
							'green-inverse': 'var(--text-other-green-inverse-color)',
							'teal-inverse': 'var(--text-other-teal-inverse-color)',
							'lightblue-inverse': 'var(--text-other-lightblue-inverse-color)',
							'blue-inverse': 'var(--text-other-blue-inverse-color)',
							'violet-inverse': 'var(--text-other-violet-inverse-color)',
							'purple-inverse': 'var(--text-other-purple-inverse-color)',
							'pink-inverse': 'var(--text-other-pink-inverse-color)',
						},
						alpha: {
							'dark-1': 'var(--text-alpha-dark-1-color)',
							'dark-2': 'var(--text-alpha-dark-2-color)',
							'dark-3': 'var(--text-alpha-dark-3-color)',
							'dark-4': 'var(--text-alpha-dark-4-color)',
							'dark-5': 'var(--text-alpha-dark-5-color)',
							'dark-6': 'var(--text-alpha-dark-6-color)',
							'dark-7': 'var(--text-alpha-dark-7-color)',
							'dark-8': 'var(--text-alpha-dark-8-color)',
							'dark-9': 'var(--text-alpha-dark-9-color)',
							'light-1': 'var(--text-alpha-light-1-color)',
							'light-2': 'var(--text-alpha-light-2-color)',
							'light-3': 'var(--text-alpha-light-3-color)',
							'light-4': 'var(--text-alpha-light-4-color)',
							'light-5': 'var(--text-alpha-light-5-color)',
							'light-6': 'var(--text-alpha-light-6-color)',
							'light-7': 'var(--text-alpha-light-7-color)',
							'light-8': 'var(--text-alpha-light-8-color)',
							'light-9': 'var(--text-alpha-light-9-color)',
						},
					},
					bg: {
						neutral: {
							base: 'var(--bg-neutral-base-color)',
							primary: 'var(--bg-neutral-primary-color)',
							secondary: 'var(--bg-neutral-secondary-color)',
							tertiary: 'var(--bg-neutral-tertiary-color)',
							quarternary: 'var(--bg-neutral-quarternary-color)',
							disabled: 'var(--bg-neutral-disabled-color)',
							inverse: 'var(--bg-neutral-inverse-color)',
							'inverse-subtle': 'var(--bg-neutral-inverse-subtle-color)',
						},
						brand: {
							primary: 'var(--bg-brand-primary-color)',
							'primary-bold': 'var(--bg-brand-primary-bold-color)',
							'primary-subtle': 'var(--bg-brand-primary-subtle-color)',
							inverse: 'var(--bg-brand-inverse-color)',
							'inverse-subtle': 'var(--bg-brand-inverse-subtle-color)',
							'inverse-bold': 'var(--bg-brand-inverse-bold-color)',
						},
						positive: {
							primary: 'var(--bg-positive-primary-color)',
							'primary-bold': 'var(--bg-positive-primary-bold-color)',
							'primary-subtle': 'var(--bg-positive-primary-subtle-color)',
							inverse: 'var(--bg-positive-inverse-color)',
						},
						info: {
							primary: 'var(--bg-info-primary-color)',
							'primary-bold': 'var(--bg-info-primary-bold-color)',
							'primary-subtle': 'var(--bg-info-primary-subtle-color)',
							inverse: 'var(--bg-info-inverse-color)',
						},
						caution: {
							primary: 'var(--bg-caution-primary-color)',
							'primary-bold': 'var(--bg-caution-primary-bold-color)',
							'primary-subtle': 'var(--bg-caution-primary-subtle-color)',
							inverse: 'var(--bg-caution-inverse-color)',
						},
						negative: {
							primary: 'var(--bg-negative-primary-color)',
							'primary-bold': 'var(--bg-negative-primary-bold-color)',
							'primary-subtle': 'var(--bg-negative-primary-subtle-color)',
							inverse: 'var(--bg-negative-inverse-color)',
						},
						other: {
							red: 'var(--bg-other-red-color)',
							'red-subtle': 'var(--bg-other-red-subtle-color)',
							'red-bold': 'var(--bg-other-red-bold-color)',
							yellow: 'var(--bg-other-yellow-color)',
							'yellow-subtle': 'var(--bg-other-yellow-subtle-color)',
							'yellow-bold': 'var(--bg-other-yellow-bold-color)',
							teal: 'var(--bg-other-teal-color)',
							'teal-subtle': 'var(--bg-other-teal-subtle-color)',
							'teal-bold': 'var(--bg-other-teal-bold-color)',
							lime: 'var(--bg-other-lime-color)',
							'lime-subtle': 'var(--bg-other-lime-subtle-color)',
							'lime-bold': 'var(--bg-other-lime-bold-color)',
							purple: 'var(--bg-other-purple-color)',
							'purple-subtle': 'var(--bg-other-purple-subtle-color)',
							'purple-bold': 'var(--bg-other-purple-bold-color)',
							violet: 'var(--bg-other-violet-color)',
							'violet-subtle': 'var(--bg-other-violet-subtle-color)',
							'violet-bold': 'var(--bg-other-violet-bold-color)',
							pink: 'var(--bg-other-pink-color)',
							'pink-subtle': 'var(--bg-other-pink-subtle-color)',
							'pink-bold': 'var(--bg-other-pink-bold-color)',
							lightblue: 'var(--bg-other-lightblue-color)',
							'lightblue-subtle': 'var(--bg-other-lightblue-subtle-color)',
							'lightblue-bold': 'var(--bg-other-lightblue-bold-color)',
							green: 'var(--bg-other-green-color)',
							'green-subtle': 'var(--bg-other-green-subtle-color)',
							'green-bold': 'var(--bg-other-green-bold-color)',
							blue: 'var(--bg-other-blue-color)',
							'blue-subtle': 'var(--bg-other-blue-subtle-color)',
							'blue-bold': 'var(--bg-other-blue-bold-color)',
							orange: 'var(--bg-other-orange-color)',
							'orange-subtle': 'var(--bg-other-orange-subtle-color)',
							'orange-bold': 'var(--bg-other-orange-bold-color)',
						},
						alpha: {
							'dark-1': 'var(--bg-alpha-dark-1-color)',
							'dark-2': 'var(--bg-alpha-dark-2-color)',
							'dark-3': 'var(--bg-alpha-dark-3-color)',
							'dark-4': 'var(--bg-alpha-dark-4-color)',
							'dark-5': 'var(--bg-alpha-dark-5-color)',
							'dark-6': 'var(--bg-alpha-dark-6-color)',
							'dark-7': 'var(--bg-alpha-dark-7-color)',
							'dark-8': 'var(--bg-alpha-dark-8-color)',
							'dark-9': 'var(--bg-alpha-dark-9-color)',
							'light-1': 'var(--bg-alpha-light-1-color)',
							'light-2': 'var(--bg-alpha-light-2-color)',
							'light-3': 'var(--bg-alpha-light-3-color)',
							'light-4': 'var(--bg-alpha-light-4-color)',
							'light-5': 'var(--bg-alpha-light-5-color)',
							'light-6': 'var(--bg-alpha-light-6-color)',
							'light-7': 'var(--bg-alpha-light-7-color)',
							'light-8': 'var(--bg-alpha-light-8-color)',
							'light-9': 'var(--bg-alpha-light-9-color)',
						},
					},
					border: {
						neutral: {
							primary: 'var(--border-neutral-primary-color)',
							secondary: 'var(--border-neutral-secondary-color)',
							tertiary: 'var(--border-neutral-tertiary-color)',
							quarternary: 'var(--border-neutral-quarternary-color)',
							disabled: 'var(--border-neutral-disabled-color)',
							inverse: 'var(--border-neutral-inverse-subtle-color)',
							'inverse-subtle': 'var(--border-neutral-inverse-subtle-color)',
						},
						brand: {
							primary: 'var(--border-brand-primary-color)',
							'primary-bold': 'var(--border-brand-primary-bold-color)',
							'primary-subtle': 'var(--border-brand-primary-subtle-color)',
							inverse: 'var(--border-brand-inverse-color)',
						},
						positive: {
							primary: 'var(--border-positive-primary-color)',
							'primary-bold': 'var(--border-positive-primary-bold-color)',
							'primary-subtle': 'var(--border-positive-primary-subtle-color)',
							inverse: 'var(--border-positive-inverse-color)',
						},
						info: {
							primary: 'var(--border-info-primary-color)',
							'primary-bold': 'var(--border-info-primary-bold-color)',
							'primary-subtle': 'var(--border-info-primary-subtle-color)',
							inverse: 'var(--border-info-inverse-color)',
						},
						caution: {
							primary: 'var(--border-caution-primary-color)',
							'primary-bold': 'var(--border-caution-primary-bold-color)',
							'primary-subtle': 'var(--border-caution-primary-subtle-color)',
							inverse: 'var(--border-caution-inverse-color)',
						},
						negative: {
							primary: 'var(--border-negative-primary-color)',
							'primary-bold': 'var(--border-negative-primary-bold-color)',
							'primary-subtle': 'var(--border-negative-primary-subtle-color)',
							inverse: 'var(--border-negative-inverse-color)',
						},
						other: {
							red: 'var(--border-other-red-color)',
							'red-subtle': 'var(--border-other-red-subtle-color)',
							'red-bold': 'var(--border-other-red-bold-color)',
							yellow: 'var(--border-other-yellow-color)',
							'yellow-subtle': 'var(--border-other-yellow-subtle-color)',
							'yellow-bold': 'var(--border-other-yellow-bold-color)',
							teal: 'var(--border-other-teal-color)',
							'teal-subtle': 'var(--border-other-teal-subtle-color)',
							'teal-bold': 'var(--border-other-teal-bold-color)',
							lime: 'var(--border-other-lime-color)',
							'lime-subtle': 'var(--border-other-lime-subtle-color)',
							'lime-bold': 'var(--border-other-lime-bold-color)',
							purple: 'var(--border-other-purple-color)',
							'purple-subtle': 'var(--border-other-purple-subtle-color)',
							'purple-bold': 'var(--border-other-purple-bold-color)',
							violet: 'var(--border-other-violet-color)',
							'violet-subtle': 'var(--border-other-violet-subtle-color)',
							'violet-bold': 'var(--border-other-violet-bold-color)',
							pink: 'var(--border-other-pink-color)',
							'pink-subtle': 'var(--border-other-pink-subtle-color)',
							'pink-bold': 'var(--border-other-pink-bold-color)',
							lightblue: 'var(--border-other-lightblue-color)',
							'lightblue-subtle': 'var(--border-other-lightblue-subtle-color)',
							'lightblue-bold': 'var(--border-other-lightblue-bold-color)',
							green: 'var(--bg-other-green-color)',
							'green-subtle': 'var(--bg-other-green-subtle-color)',
							'green-bold': 'var(--bg-other-green-bold-color)',
							blue: 'var(--border-other-blue-color)',
							'blue-subtle': 'var(--border-other-blue-subtle-color)',
							'blue-bold': 'var(--border-other-blue-bold-color)',
							orange: 'var(--border-other-orange-color)',
							'orange-subtle': 'var(--border-other-orange-subtle-color)',
							'orange-bold': 'var(--border-other-orange-bold-color)',
							'red-inverse': 'var(--border-other-red-inverse-color)',
							'yellow-inverse': 'var(--border-other-yellow-inverse-color)',
							'orange-inverse': 'var(--border-other-orange-inverse-color)',
							'lime-inverse': 'var(--border-other-lime-inverse-color)',
							'green-inverse': 'var(--border-other-green-inverse-color)',
							'teal-inverse': 'var(--border-other-teal-inverse-color)',
							'lightblue-inverse': 'var(--border-other-lightblue-inverse-color)',
							'blue-inverse': 'var(--border-other-blue-inverse-color)',
							'violet-inverse': 'var(--border-other-violet-inverse-color)',
							'purple-inverse': 'var(--border-other-purple-inverse-color)',
							'pink-inverse': 'var(--border-other-pink-inverse-color)',
						},
						alpha: {
							'dark-1': 'var(--bg-alpha-dark-1-color)',
							'dark-2': 'var(--bg-alpha-dark-2-color)',
							'dark-3': 'var(--bg-alpha-dark-3-color)',
							'dark-4': 'var(--bg-alpha-dark-4-color)',
							'dark-5': 'var(--bg-alpha-dark-5-color)',
							'dark-6': 'var(--bg-alpha-dark-6-color)',
							'dark-7': 'var(--bg-alpha-dark-7-color)',
							'dark-8': 'var(--bg-alpha-dark-8-color)',
							'dark-9': 'var(--bg-alpha-dark-9-color)',
							'light-1': 'var(--bg-alpha-light-1-color)',
							'light-2': 'var(--bg-alpha-light-2-color)',
							'light-3': 'var(--bg-alpha-light-3-color)',
							'light-4': 'var(--bg-alpha-light-4-color)',
							'light-5': 'var(--bg-alpha-light-5-color)',
							'light-6': 'var(--bg-alpha-light-6-color)',
							'light-7': 'var(--bg-alpha-light-7-color)',
							'light-8': 'var(--bg-alpha-light-8-color)',
							'light-9': 'var(--bg-alpha-light-9-color)',
						},
					},
					icon: {
						neutral: {
							primary: 'var(--icon-neutral-primary-color)',
							secondary: 'var(--icon-neutral-secondary-color)',
							tertiary: 'var(--icon-neutral-tertiary-color)',
							quarternary: 'var(--icon-neutral-quarternary-color)',
							disabled: 'var(--icon-neutral-disabled-color)',
							inverse: 'var(--icon-neutral-inverse-color)'
						},
						alert: {
							primary: 'var(--icon-alert-primary-color)',
						},
						brand: {
							primary: 'var(--icon-brand-primary-color)',
							'primary-bold': 'var(--icon-brand-primary-bold-color)',
							'primary-subtle': 'var(--icon-brand-primary-subtle-color)',
							inverse: 'var(--icon-brand-inverse-color)'
						},
						positive: {
							primary: 'var(--icon-positive-primary-color)',
							'primary-bold': 'var(--icon-positive-primary-bold-color)',
							'primary-subtle': 'var(--icon-positive-primary-subtle-color)',
							inverse: 'var(--icon-positive-inverse-color)',
						},
						info: {
							primary: 'var(--icon-info-primary-color)',
							'primary-bold': 'var(--icon-info-primary-bold-color)',
							'primary-subtle': 'var(--icon-info-primary-subtle-color)',
							inverse: 'var(--icon-positive-inverse-color)',
						},
						caution: {
							primary: 'var(--icon-caution-primary-color)',
							'primary-bold': 'var(--icon-caution-primary-bold-color)',
							'primary-subtle': 'var(--icon-caution-primary-subtle-color)',
							inverse: 'var(--icon-caution-inverse-color)',
						},
						negative: {
							primary: 'var(--icon-negative-primary-color)',
							'primary-bold': 'var(--icon-negative-primary-bold-color)',
							'primary-subtle': 'var(--icon-negative-primary-subtle-color)',
							inverse: 'var(--icon-negative-inverse-color)',
						},
						other: {
							red: 'var(--icon-other-red-color)',
							'red-subtle': 'var(--icon-other-red-subtle-color)',
							'red-bold': 'var(--icon-other-red-bold-color)',
							yellow: 'var(--icon-other-yellow-color)',
							'yellow-subtle': 'var(--icon-other-yellow-subtle-color)',
							'yellow-bold': 'var(--icon-other-yellow-bold-color)',
							teal: 'var(--icon-other-teal-color)',
							'teal-subtle': 'var(--icon-other-teal-subtle-color)',
							'teal-bold': 'var(--icon-other-teal-bold-color)',
							lime: 'var(--icon-other-lime-color)',
							'lime-subtle': 'var(--icon-other-lime-subtle-color)',
							'lime-bold': 'var(--icon-other-lime-bold-color)',
							purple: 'var(--icon-other-purple-color)',
							'purple-subtle': 'var(--icon-other-purple-subtle-color)',
							'purple-bold': 'var(--icon-other-purple-bold-color)',
							violet: 'var(--icon-other-violet-color)',
							'violet-subtle': 'var(--icon-other-violet-subtle-color)',
							'violet-bold': 'var(--icon-other-violet-bold-color)',
							pink: 'var(--icon-other-pink-color)',
							'pink-subtle': 'var(--icon-other-pink-subtle-color)',
							'pink-bold': 'var(--icon-other-pink-bold-color)',
							lightblue: 'var(--icon-other-lightblue-color)',
							'lightblue-subtle': 'var(--icon-other-lightblue-subtle-color)',
							'lightblue-bold': 'var(--icon-other-lightblue-bold-color)',
							green: 'var(--icon-other-green-color)',
							'green-subtle': 'var(--icon-other-green-subtle-color)',
							'green-bold': 'var(--icon-other-green-bold-color)',
							blue: 'var(--icon-other-blue-color)',
							'blue-subtle': 'var(--icon-other-blue-subtle-color)',
							'blue-bold': 'var(--icon-other-blue-bold-color)',
							orange: 'var(--icon-other-orange-color)',
							'orange-subtle': 'var(--icon-other-orange-subtle-color)',
							'orange-bold': 'var(--icon-other-orange-bold-color)',
							'red-inverse': 'var(--icon-other-red-inverse-color)',
							'yellow-inverse': 'var(--icon-other-yellow-inverse-color)',
							'orange-inverse': 'var(--icon-other-orange-inverse-color)',
							'lime-inverse': 'var(--icon-other-lime-inverse-color)',
							'green-inverse': 'var(--icon-other-green-inverse-color)',
							'teal-inverse': 'var(--icon-other-teal-inverse-color)',
							'lightblue-inverse': 'var(--icon-other-lightblue-inverse-color)',
							'blue-inverse': 'var(--icon-other-blue-inverse-color)',
							'violet-inverse': 'var(--icon-other-violet-inverse-color)',
							'purple-inverse': 'var(--icon-other-purple-inverse-color)',
							'pink-inverse': 'var(--icon-other-pink-inverse-color)',
						},
					},
					toggle: {
						hover: {
							color: 'var(--toggle-hover-color)',
						}
					},
					
				}
			},
			zIndex: {
				0: 0,
				1: 1,
				2: 2,
				3: 3,
				4: 4,
				5: 5,
				6: 6,
				7: 7,
				8: 8,
				9: 9,
				10: 10,
				11: 11,
				15: 15,
				20: 20,
				25: 25,
				30: 30,
				35: 35,
				40: 40,
				45: 45,
				50: 50,
				100: 100,
				auto: 'auto'
			}
		},
	},
	variants: {
		extend: {
			colors: ['hover', 'focus'],
		},
	},
	plugins: [],
}

export default config
